src/main/java/site/campingon/campingon/user/entity/Role.java
src/main/java/site/campingon/campingon/user/entity/User.java
src/main/java/site/campingon/campingon/user/repository/UserRepository.java
src/main/resources/application.yml

User 도메인에서 사용할 User Entity와 Repository 구현
- User.java, Role.java, UserRepository 추가
- application.yml 파일 변경
3. [ ] 기타:
- H2 자체에서는 Unsigned를 지원하지 않는 문제가 있었습니다.
- application.yml 파일에 `MODE=MYSQL`을 추가하여 해결하였습니다.
- 로그
```
024-11-21T17:00:21.807+09:00  WARN 32042 --- [  restartedMain] o.h.t.s.i.ExceptionHandlerLoggedImpl     : GenerationTarget encountered exception accepting command : Error executing DDL "
create table users (
id INT UNSIGNED generated by default as identity,
created_at DATETIME not null,
modified_at DATETIME not null,
delete_reason TEXT,
deleted_at …
```

feat: #2 User Entity & Repository 구현

---

.gitignore

feat : gitignore .env 추가

---

src/main/java/site/campingon/campingon/camp/entity/Camp.java
src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
src/main/java/site/campingon/campingon/camp/entity/CampImage.java
src/main/java/site/campingon/campingon/camp/entity/CampInfo.java
src/main/java/site/campingon/campingon/camp/entity/CampKeyword.java
src/main/java/site/campingon/campingon/camp/entity/CampSite.java

추가 기능 개발을 위해서
X
Camp, CampSite, CampKeyword, CampInfo, CampImage, CampAddr 엔티티 생성
X
X
- Closes #

[FEAT] Camp 관련 Entity들 생성

---

src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingRequestDto.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingResponseDto.java
src/main/java/site/campingon/campingon/common/public_data/mapper/GoCampingMapper.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

공공API 응답데이터 필터링
3. [ ] 기타:
- Closes #15

Feat/#15 camp 공공API 응답데이터 필터링

---

src/main/java/site/campingon/campingon/camp/repository/CampAddrRepository.java
src/main/java/site/campingon/campingon/camp/repository/CampImageRepository.java
src/main/java/site/campingon/campingon/camp/repository/CampInfoRepository.java
src/main/java/site/campingon/campingon/camp/repository/CampKeywordRepository.java
src/main/java/site/campingon/campingon/camp/repository/CampRepository.java
src/main/java/site/campingon/campingon/camp/repository/CampSiteRepository.java
src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingRequestDto.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingResponseDto.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

공공데이터 DB저장
- 공공데이터 타입 변경
- Camp관련 Repository 구현
- CampController 제너럴 타입 변경
- config 설정 모든 경로 허가 변경
3. [ ] 기타:
- 캠핑장 ContentId는 엔티티가 autoincrement 전략이라 주석처리했습니다.
- CampSite 경우 maximumPeople, price 컬럼이 not null 조건이여서 임시적으로 설정했습니다.
- Closes #26

Feat/#26 공공데이터 DB저장

---

src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
src/main/java/site/campingon/campingon/user/controller/CampController.java
src/main/java/site/campingon/campingon/user/controller/UserController.java
src/main/java/site/campingon/campingon/user/dto/UserDeactivateRequestDto.java
src/main/java/site/campingon/campingon/user/dto/UserUpdateRequestDto.java
src/main/java/site/campingon/campingon/user/mapper/CampMapper.java
src/main/java/site/campingon/campingon/user/mapper/UserMapper.java
src/main/java/site/campingon/campingon/user/repository/UserRepository.java
src/main/java/site/campingon/campingon/user/service/CampService.java
src/main/java/site/campingon/campingon/user/service/UserService.java
src/test/java/site/campingon/campingon/user/service/UserServiceTest.java

JWT 관련을 제외한 기본적인 UserService 구현
- `UserService` 클래스에 회원 가입, 조회, 수정, 탈퇴 메서드 추가
- `SecurityConfig`에 비밀번호 암호화를 위한 Encoder 등록
- UserService에 대한 유닛 테스트 진행
3. [ ] 기타:
- Security Config 파일이 수정되었습니다.
- 로그인과 로그아웃의 경우 JWT 부분 구현 이후에 진행할 예정입니다.
- Closes #32

feat: #32 User 관련 기본 서비스 및 테스트 코드 생성

---

src/main/java/site/campingon/campingon/common/public_data/GoCampingPath.java
src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingDataDto.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingParsedResponseDto.java
src/main/java/site/campingon/campingon/common/public_data/mapper/GoCampingMapper.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

1주차 코드리뷰 피드백 반영
3. [ ] 기타:
- Closes #44

Feat/#44 - 1주차 코드리뷰 피드백 반영

---

src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/common/exception/ErrorResponse.java
src/main/java/site/campingon/campingon/common/exception/GlobalException.java
src/main/java/site/campingon/campingon/common/exception/GlobalExceptionHandler.java

전역예외처리 설계 완료
기존의 예외처리 코드는 설계한 예외처리에 맞게 수정해주시면 됩니다.
3. [ ] 기타:
- 커스텀 에러코드를 예시처럼 추가해주세요. 상태코드에 대한 공부가 필요합니다.
- 상태코드는 바디에서 체크할 사항이 아닙니다. 헤더에 있어야합니다.
- Closes #37 Closes #38 Closes #39

Feat/#37 전역예외처리 설계 완료

---

src/main/java/site/campingon/campingon/bookmark/controller/CampController.java
src/main/java/site/campingon/campingon/bookmark/entity/BookMark.java
src/main/java/site/campingon/campingon/bookmark/mapper/CampMapper.java
src/main/java/site/campingon/campingon/bookmark/repository/BookMarkRepository.java
src/main/java/site/campingon/campingon/bookmark/service/CampService.java
src/main/java/site/campingon/campingon/camp/controller/CampController.java
src/main/java/site/campingon/campingon/camp/dto/CampDetailResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/CampListResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
src/main/java/site/campingon/campingon/camp/entity/Camp.java
src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
src/main/java/site/campingon/campingon/camp/entity/CampInfo.java
src/main/java/site/campingon/campingon/camp/entity/CampSite.java
src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
src/main/java/site/campingon/campingon/camp/service/CampService.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
src/main/java/site/campingon/campingon/like/controller/CampController.java
src/main/java/site/campingon/campingon/like/dto/CampDto.java
src/main/java/site/campingon/campingon/like/mapper/CampMapper.java
src/main/java/site/campingon/campingon/like/service/CampService.java

1주차 코드리뷰와 팀스크럼과 오피스아워 내용 반영하여 수정 
- 공공 API 필드 확인하여 CampAddr 적용과 @PreAuthorize("isAuthenticated()") 제거
- Like -> BookMark 도메인 수정
- Camp, CampAddr, CampInfo, CampSite 엔티티 필드 추가
- 수정한 필드에 대한 CampMapper, CampService, CampDto 수정 
- 키워드 추천은 Matched, 캠핑장 추천은 recommend
3. [ ] 기타:
- Closes #43

Feat/#43 코드리뷰 수정 + 스크럼 내용 반영 + API명세서 수정 

---

src/main/java/site/campingon/campingon/camp/controller/CampSiteAdminController.java
src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteCreateRequestDto.java
src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteUpdateRequestDto.java
src/main/java/site/campingon/campingon/camp/mapper/CampSiteMapper.java
src/main/java/site/campingon/campingon/camp/repository/CampSiteRepository.java
src/main/java/site/campingon/campingon/camp/service/CampSiteService.java

> 캠핑장 관리자의 CRUD 기능을 구현하기 위해서
컨트롤러
<br/>
Dto
<br/>
매퍼
<br/>
레파지토리
<br/>
서비스
코드명명 규칙에 맞게 작성
CampAdminController와 CampSiteAdminController에 중복 로직(getCampSites 메서드)가 존재함
CampSiteRepository에 있는 삭제 코드(findByIdAndCampId)를 soft Delete, hard Delete 중 어떤 것으로 할지 오전 스크럼때 논의 필요
- Closes #

Feat/#68  CampSiteAdminController 작성

---

src/main/java/site/campingon/campingon/camp/controller/CampAdminController.java
src/main/java/site/campingon/campingon/camp/dto/admin/CampCreateRequestDto.java
src/main/java/site/campingon/campingon/camp/dto/admin/CampUpdateRequestDto.java
src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
src/main/java/site/campingon/campingon/camp/service/CampService.java

코드량이 너무 많고 해결 못하는 문제가 생겨서
캠핑장과 캠핑지의 관리자 CRUD 기능구현을 나누어서 PR요청
Dto 부분 명명 규칙에 맞게 수정
3. [ ] 기타:
- Closes #

Feat/#66  CampAdminController 작성

---

src/main/java/site/campingon/campingon/bookmark/controller/BookMarkController.java
src/main/java/site/campingon/campingon/bookmark/controller/CampController.java
src/main/java/site/campingon/campingon/bookmark/entity/Bookmark.java
src/main/java/site/campingon/campingon/bookmark/repository/BookmarkRepository.java
src/main/java/site/campingon/campingon/bookmark/service/BookmarkService.java
src/main/java/site/campingon/campingon/bookmark/service/CampService.java
src/main/java/site/campingon/campingon/camp/controller/CampController.java
src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
src/main/java/site/campingon/campingon/camp/entity/Camp.java
src/main/java/site/campingon/campingon/camp/entity/CampSite.java
src/main/java/site/campingon/campingon/camp/repository/CampRepository.java
src/main/java/site/campingon/campingon/camp/service/CampService.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

CampController의 찜 등록과 해제 기능을 BookMark 도메인으로 구현
CampController의 찜한 캠핑장 목록 조회 구현
- CampController, Service의 getBookmarkedCamps 메서드 추가
- BookmarkController, Service의 bookmarkCamp, unbookmarkCamp 메서드 추가
- CampSite 필드 roomName 제거 
3. [ ] 기타:
- Closes #53, Closes #54 , Closes #55

Feat/#53 Bookmark 도메인 서비스 분리 및 구축

---

src/main/java/site/campingon/campingon/camp/dto/CampDetailResponseDto.java
src/main/java/site/campingon/campingon/camp/entity/Camp.java
src/main/java/site/campingon/campingon/camp/entity/CampInduty.java
src/main/java/site/campingon/campingon/camp/entity/CampSite.java
src/main/java/site/campingon/campingon/camp/entity/Induty.java
src/main/java/site/campingon/campingon/camp/repository/CampIndutyRepository.java
src/main/java/site/campingon/campingon/common/converter/IndutyConverter.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingDataDto.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingParsedResponseDto.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

- 공공데이터로부터 엔티티에 저장
3. [ ] 기타:
- Closes #65

Feat/#65 Camp, CampSite 엔티티와 GoCampingService 수정

---

src/main/java/site/campingon/campingon/common/config/oauth/CustomOAuth2UserService.java
src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/common/jwt/JwtAuthenticationFilter.java
src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
src/main/java/site/campingon/campingon/common/jwt/RefreshToken.java
src/main/java/site/campingon/campingon/common/jwt/RefreshTokenService.java
src/main/java/site/campingon/campingon/common/util/CookieUtil.java
src/main/java/site/campingon/campingon/user/controller/UserAuthController.java
src/main/java/site/campingon/campingon/user/controller/UserController.java
src/main/java/site/campingon/campingon/user/entity/Role.java
src/main/java/site/campingon/campingon/user/mapper/UserMapper.java
src/main/java/site/campingon/campingon/user/service/UserAuthService.java
src/main/java/site/campingon/campingon/user/service/UserService.java

JWT 토큰을 쿠키에 저장해 인증하는 방식 구현
-  UserAuthService, UserAuthController 추가
- [UserController 회원 정보 조회 api 추가
- Role enum 클래스에서 GrantedAuthority 상속
2. [x] 로컬 환경에서 직접 테스트(포스트맨, 리액트)
3. [ ] 기타:
- Closes #71

Feat/#71 JWT 토큰 이용 로그인 구현

---

src/main/java/site/campingon/campingon/camp/entity/Camp.java
src/main/java/site/campingon/campingon/common/converter/IndutyConverter.java
src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingImageDto.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingImageParsedResponseDto.java
src/main/java/site/campingon/campingon/common/public_data/mapper/GoCampingMapper.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

- CampImage DB를 저장
- 커스텀 예외처리
- Camp Id의 autoIncrement 전략부분 삭제
- 커스텀 예외처리
3. [ ] 기타:
- Closes #64

Feat/#64 CampImage DB 저장 및 커스텀 예외처리

---

src/main/java/site/campingon/campingon/camp/entity/Camp.java
src/main/java/site/campingon/campingon/camp/entity/CampInduty.java
src/main/java/site/campingon/campingon/camp/entity/CampSite.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

- 공공데이터 생성일, 수정일 저장
3. [ ] 기타:
- Closes #78

Feat/#78 공공데이터 생성일, 수정일 저장

---

src/main/resources/application-s3Bucket.yml

Spring app 포트 번호 8080으로 복귀
3. [ ] 기타:
- Closes #90

Fix: #90 application-s3Bucket.yml에서 포트 제거

---

src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

- DB에 있는 Camp 데이터에 이미지를 추가로 저장한다.
3. [ ] 기타:
- Closes #80 
- Closes #79

Feat/#80 Camp ID가 가지고 있는 CampImage 저장 구현

---

src/main/java/site/campingon/campingon/common/entity/BaseEntity.java
src/main/java/site/campingon/campingon/common/oauth/TestController.java
src/main/java/site/campingon/campingon/common/oauth/service/CustomOAuth2UserService.java
src/main/java/site/campingon/campingon/reservation/controller/CampController.java
src/main/java/site/campingon/campingon/reservation/controller/ReservationController.java
src/main/java/site/campingon/campingon/reservation/dto/CampDto.java
src/main/java/site/campingon/campingon/reservation/dto/ReservationCreatedRequestDto.java
src/main/java/site/campingon/campingon/reservation/dto/ReservationResponseDto.java
src/main/java/site/campingon/campingon/reservation/entity/Camp.java
src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
src/main/java/site/campingon/campingon/reservation/entity/ReservationStatus.java
src/main/java/site/campingon/campingon/reservation/mapper/CampMapper.java
src/main/java/site/campingon/campingon/reservation/mapper/ReservationMapper.java
src/main/java/site/campingon/campingon/reservation/repository/CampRepository.java
src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
src/main/java/site/campingon/campingon/reservation/service/CampService.java
src/main/java/site/campingon/campingon/reservation/service/ReservationService.java
src/main/java/site/campingon/campingon/user/entity/User.java

예약 필수 클래스 생성
- LocalDateTime 필드 포맷 변경 - 밀리초 제거
3. [ ] 기타:
- Closes #97 Closes #98 Closes #99 Closes #96

Feat/#96 reservation 예약 필수 클래스 생성

---

src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/admin/CampCreateRequestDto.java
src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteCreateRequestDto.java
src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteUpdateRequestDto.java
src/main/java/site/campingon/campingon/camp/dto/admin/CampUpdateRequestDto.java
src/main/java/site/campingon/campingon/camp/entity/CampSite.java
src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
src/main/java/site/campingon/campingon/camp/mapper/CampSiteMapper.java
src/main/java/site/campingon/campingon/camp/repository/CampSiteRepository.java
src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
src/main/java/site/campingon/campingon/review/controller/CampController.java
src/main/java/site/campingon/campingon/review/entity/Camp.java
src/main/java/site/campingon/campingon/review/mapper/CampMapper.java
src/main/java/site/campingon/campingon/review/repository/CampRepository.java
src/main/java/site/campingon/campingon/review/service/CampService.java
src/test/java/site/campingon/campingon/camp/repository/CampSiteRepositoryTest.java
src/test/java/site/campingon/campingon/camp/service/CampSiteServiceTest.java

캠핑지 생성 기능 테스트를 추가하여 모든 유형의 Induty에 대해 캠핑지가 정상적으로 생성되는지 확인하고, 서비스 로직이 기대한 대로 동작하는지 검증하기 위함입니다.
- CampSiteServiceTest 클래스에 캠핑지 생성을 위한 새로운 테스트 케이스 추가
- 모든 Induty 유형에 대해 캠핑지를 생성하고 검증하는 테스트 메서드 추가
- Mock을 통해 campRepository, campSiteMapper의 동작을 시뮬레이션하고, 반환값을 설정함
1. [ ] 모든 유형의 Induty 필드를 테스트하는 테스트 케이스 작성 (testCreateCampSiteWithAllInduties)
2. [ ] 로컬 환경에서 JUnit을 사용하여 테스트 실행 및 확인
- Closes #

Feat/#104 CampSite 수정 & 테스트 코드 추가

---

src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteCreateRequestDto.java
src/main/java/site/campingon/campingon/camp/dto/admin/CampSiteUpdateRequestDto.java
src/main/java/site/campingon/campingon/camp/entity/CampSite.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
src/test/java/site/campingon/campingon/camp/service/CampSiteServiceTest.java

Feat/#110 CampSite 수정 & 테스트 코드 추가, 피드백 반영3

---

src/main/java/site/campingon/campingon/common/converter/ReservationStatusConverter.java
src/main/java/site/campingon/campingon/common/entity/BaseEntity.java
src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/common/oauth/handler/CustomOAuth2FailureHandler.java
src/main/java/site/campingon/campingon/common/oauth/handler/CustomOAuthSuccessHandler.java
src/main/java/site/campingon/campingon/common/oauth/service/CustomOAuth2UserService.java
src/main/java/site/campingon/campingon/reservation/dto/ReservationCancelRequestDto.java
src/main/java/site/campingon/campingon/reservation/dto/ReservationCreateRequestDto.java
src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
src/main/java/site/campingon/campingon/reservation/entity/ReservationStatus.java
src/main/java/site/campingon/campingon/reservation/mapper/ReservationMapper.java

reservation 컨버터, 매퍼, dto 완료
- 예약 엔티티에 예약취소이유 컬럼 추가
- 에러코드 추가
- oauth 관련 코드 스타일 변경
- 불필요한 날짜 포맷 삭제
3. [ ] 기타:
- 예약상태를 가져오려면 `ReservationStatus.RESERVED.getStatus()` 하면 됨
- Closes #107

Feat/#107 reservation 컨버터, 매퍼, dto 완료

---

build.gradle
src/main/java/site/campingon/campingon/CampingOnBeApplication.java
src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
src/main/java/site/campingon/campingon/camp/repository/CampAddrRepository.java
src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
src/main/resources/application.yml

- CampAddr location 타입 import jti 로 변경
- spatial 의존성추가
3. [ ] 기타:
- 애플리케이션은 실행되나 location 값은 넘어오지않음...
- 이미지 데이터 DB저장에서 문제가 발생함... (이슈등록)
- Closes #114 
- Closes #120

Feat/#89 h2->mysql 이동, 스프링 스케줄러 추가

---

src/main/java/site/campingon/campingon/user/entity/User.java
src/main/java/site/campingon/campingon/user/entity/UserKeyword.java

Lazy loading으로 발생하는 LazyInitializationException 해결
- User.java: toString overriding
- toString 내부에서 Lazy Loading 되는 속성 제거
- UserKeyword.java: toString override
3. [ ] 기타:
- Closes #127, #109

Fix: #127 LazyInitializationException 해결

---

src/main/java/site/campingon/campingon/camp/dto/CampAddrResponseDto.java
src/main/java/site/campingon/campingon/common/converter/ReservationStatusConverter.java
src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/reservation/controller/ReservationController.java
src/main/java/site/campingon/campingon/reservation/dto/CampAddrResponseDto.java
src/main/java/site/campingon/campingon/reservation/dto/CampResponseDto.java
src/main/java/site/campingon/campingon/reservation/dto/ReservationCheckDateRequestDto.java
src/main/java/site/campingon/campingon/reservation/dto/ReservationCreateRequestDto.java
src/main/java/site/campingon/campingon/reservation/dto/ReservationResponseDto.java
src/main/java/site/campingon/campingon/reservation/dto/ReservedCampSiteIdListResponseDto.java
src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
src/main/java/site/campingon/campingon/reservation/entity/ReservationStatus.java
src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
src/main/java/site/campingon/campingon/reservation/service/ReservationService.java
src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java
src/main/java/site/campingon/campingon/reservation/utils/ReservationValidate.java
src/main/resources/application.yml
src/test/java/site/campingon/campingon/reservation/service/ReservationServiceTest.java

reservation api 구현 완료
- 에러코드 추가
- 예약상태 컨버터 변경 (DB에 영문, json으로는 한글 반환)
- application.yml 에 페이지네이션 변수 추가
3. [ ] 기타:
API 명세서에 작성할게용
- Closes #122, Closes #123, Closes #124, Closes #125, Closes #126, Closes #108

Feat/#107 reservation api 구현 완료

---

src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java

- `ReservationServiceImpl.java ` `@Transactional`추가
3. [ ] 기타:

refactor: 예약 비즈니스 로직에 @Transactional 추가

---

src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
src/main/java/site/campingon/campingon/user/service/UserService.java

Custom Error Code를 사용하여 더 쉬운 에러 파악
- ErrorCode 일부 수정
3. [ ] 기타:
- 로그아웃에서 발생하는 RuntimeException은 예상하지 못한 에러라 그대로 RuntimeException을 사용하였습니다.
- Closes #135

Feat: #135 User 관련 메서드 Custome Error Code 적용

---

src/main/java/site/campingon/campingon/bookmark/service/BookmarkService.java
src/main/java/site/campingon/campingon/camp/controller/CampController.java
src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
src/main/java/site/campingon/campingon/camp/entity/Camp.java
src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
src/main/java/site/campingon/campingon/camp/service/CampService.java
src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java

- Bookmark, campSite 커스텀 익셉션 설정 및 리팩토링
3. [ ] 기타:
- Closes #

[IMPROVE] #142 - 2주차 코드리뷰 수정

---

src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
src/main/java/site/campingon/campingon/camp/service/CampSiteService.java
src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/review/service/ReviewService.java
src/test/java/site/campingon/campingon/review/service/ReviewServiceTest.java

2주차 코드 피드백 반영
ErrorCode에 커스텀 로직 작성 후, 캠핑지 서비스와 리뷰 서비스에 커스텀 로직 추가
- ErrorCode
- CampSiteService
- ReviewService
- ReviewServiceTest
- 테스트코드 작성후 확인

Feat/#141 CampSiteService, ReviewService에 커스텀 예외 로직 추가

---

src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/common/jwt/CustomAccessDeniedHandler.java
src/main/java/site/campingon/campingon/common/jwt/CustomAuthenticationEntryPoint.java
src/main/java/site/campingon/campingon/common/jwt/JwtAuthenticationFilter.java
src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
src/main/java/site/campingon/campingon/common/jwt/RefreshToken.java
src/main/java/site/campingon/campingon/common/jwt/RefreshTokenService.java
src/main/java/site/campingon/campingon/user/dto/UserSignInRequestDto.java
src/main/java/site/campingon/campingon/user/dto/UserSignUpRequestDto.java
src/main/java/site/campingon/campingon/user/dto/UserUpdateRequestDto.java
src/main/java/site/campingon/campingon/user/service/UserAuthService.java

2주차 코드리뷰 중 유저와 토큰 관련 사항을 반영함
- refresh token의 값이 JWT 형식에서 UUID로 변경되었습니다.
- EntryPoint, DeniedHandler가 추가 되었습니다.
- Size 어노테이션 대신 regex에 최소, 최대 값을 설정하였습니다.
- 토큰 재발급 시 동시성 제어를 위해 ReentrantLock를 도입해봤습니다.
3. [ ] 기타:
- Closes #145

Feat: #145 유저 관련 코드 리뷰 반영

---

src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java

Feat: #145 throw 구문 제거

---

src/main/java/site/campingon/campingon/camp/entity/CampInfo.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

- camp, campInfo 조인시 조회가 안되는문제 해결
- CampInfo 추천수, 찜수 기본 0으로 설정
- CampInfo 생성 추가
3. [ ] 기타:
- Closes #159

fix : #159 camp, campInfo 조인시 조회가 안되는문제

---

build.gradle
src/main/java/site/campingon/campingon/CampingOnBeApplication.java
src/main/java/site/campingon/campingon/camp/controller/CampController.java
src/main/java/site/campingon/campingon/camp/controller/mongodb/SearchInfoController.java
src/main/java/site/campingon/campingon/camp/dto/CampListResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
src/main/java/site/campingon/campingon/camp/entity/mongodb/SearchInfo.java
src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
src/main/java/site/campingon/campingon/camp/repository/mongodb/SearchInfoRepository.java
src/main/java/site/campingon/campingon/camp/service/CampService.java
src/main/java/site/campingon/campingon/camp/service/mongodb/SearchInfoService.java
src/main/java/site/campingon/campingon/common/config/SecurityPath.java
src/main/java/site/campingon/campingon/common/s3bucket/config/S3Config.java
src/main/java/site/campingon/campingon/common/s3bucket/controller/S3BucketController.java
src/main/java/site/campingon/campingon/common/s3bucket/service/S3BucketService.java
src/main/java/site/campingon/campingon/review/service/ReviewService.java
src/main/java/site/campingon/campingon/user/repository/UserKeywordRepository.java
src/main/resources/application.yml
src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java
src/test/java/site/campingon/campingon/camp/service/CampSiteServiceTest.java
src/test/java/site/campingon/campingon/review/service/ReviewServiceTest.java

- 지역 우선적 검색 후 캠핑장명 검색 + 페이지네이션 적용으로 수정
3. [ ] 기타:
- Closes #162

Feat/#162 mongoDB 검색 내용 페이지네이션 적용, 지역 우선순위로 변경

---

src/main/java/site/campingon/campingon/camp/controller/mongodb/SearchInfoController.java
src/main/java/site/campingon/campingon/camp/entity/mongodb/SearchInfo.java
src/main/java/site/campingon/campingon/common/config/SecurityPath.java

fix: SearchInfo의 campId Long타입 변경, SearchInfoController 엔드포인트 변경

---

src/main/java/site/campingon/campingon/camp/controller/CampController.java
src/main/java/site/campingon/campingon/camp/dto/CampListResponseDto.java
src/main/java/site/campingon/campingon/camp/entity/Camp.java
src/main/java/site/campingon/campingon/camp/repository/CampIndutyRepository.java
src/main/java/site/campingon/campingon/camp/repository/CampInfoRepository.java
src/main/java/site/campingon/campingon/camp/service/CampService.java
src/main/java/site/campingon/campingon/common/jwt/CustomUserDetails.java
src/main/java/site/campingon/campingon/common/jwt/CustomUserDetailsService.java
src/main/java/site/campingon/campingon/common/jwt/CustomUserPrincipal.java
src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
src/main/java/site/campingon/campingon/common/oauth/CustomOAuth2User.java
src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingProviderService.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
src/main/java/site/campingon/campingon/user/service/UserAuthService.java
src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java

- api  호출시 인증된 유저정보에서 name이 필요할 때를 대비해 필드추가
- jwt body name 추가
- CustomUserDetails name 필드추가
3. [ ] 기타:
- Closes #165

Feat/#165  CustomUserDetails name 필드 추가

---

src/main/java/site/campingon/campingon/camp/controller/CampController.java
src/main/java/site/campingon/campingon/camp/dto/CampListResponseDto.java
src/main/java/site/campingon/campingon/camp/entity/Camp.java
src/main/java/site/campingon/campingon/camp/repository/CampIndutyRepository.java
src/main/java/site/campingon/campingon/camp/repository/CampInfoRepository.java
src/main/java/site/campingon/campingon/camp/service/CampService.java
src/main/java/site/campingon/campingon/common/jwt/CustomUserDetails.java
src/main/java/site/campingon/campingon/common/jwt/CustomUserDetailsService.java
src/main/java/site/campingon/campingon/common/jwt/CustomUserPrincipal.java
src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
src/main/java/site/campingon/campingon/common/oauth/CustomOAuth2User.java
src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingProviderService.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
src/main/java/site/campingon/campingon/user/service/UserAuthService.java
src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java

- Camp, Camp_Info 문제는 생기지 않습니다
- Camp, Camp_Info 엔티티 생성과정에서 생기는 왜래키 문제 해결
- 같은 데이터 DB저장시 CampInduty 데이터가 중복해서 저장되는 문제 해결
3. [ ] 기타:
- Closes #167 
- Closes #168

Fix/#167 camp, Camp_Info 생성 문제

---

src/main/java/site/campingon/campingon/camp/controller/CampSiteAdminController.java

캠프사이트 api 정리 중
3. [ ] 기타:
- Closes #174

refactor: #174 캠프사이트 api url 수정

---

src/main/java/site/campingon/campingon/camp/entity/Induty.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

maximum_people -> maximumPeople 변경
maximum_people -> maximumPeople 변경
3. [ ] 기타:
- Closes #176

style : #176 maximum_people -> maximumPeople 변경

---

src/main/java/site/campingon/campingon/camp/controller/CampController.java
src/main/java/site/campingon/campingon/camp/controller/CampSiteAdminController.java
src/main/java/site/campingon/campingon/camp/controller/mongodb/SearchInfoController.java
src/main/java/site/campingon/campingon/camp/dto/CampDetailResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/CampListResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
src/main/java/site/campingon/campingon/camp/mapper/CampSiteMapper.java
src/main/java/site/campingon/campingon/camp/repository/CampIndutyRepository.java
src/main/java/site/campingon/campingon/common/config/SecurityPath.java
src/main/resources/application.yml
src/main/resources/logback-spring.xml
src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java

Camp 가독성 향상 및 최적화 목적 
- CampDto명 id -> campId로 수정
-  SearchInfoController 엔드포인트 수정, 페이지 단위로 묶어서 사용 (application.yml에 정의)
- SecurityPath경로 수정 
- CampController searchCamps 메서드 주석처리(mongoDB 이용)
3. [ ] 기타:
- Closes #

Refactor: #179 camp 피드백 반영 수정 

---

src/main/java/site/campingon/campingon/camp/dto/CampAddrDto.java
src/main/java/site/campingon/campingon/camp/dto/CampDetailResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/CampInfoDto.java
src/main/java/site/campingon/campingon/camp/mapper/CampMapper.java
src/main/java/site/campingon/campingon/camp/service/CampService.java
src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/review/controller/ReviewController.java
src/main/java/site/campingon/campingon/review/service/ReviewService.java

캠핑장 상세 조회 페이지를 구현하기 위해서
- 양방향 관계에서 직렬화 문제를 막기위해 dto를 추가함
2. [o] 로컬 환경에서 직접 테스트
3. [ ] 기타:
- Closes #

Feat/#183 CampAddrDto, CampInfoDto 추가

---

.github/workflows/deploy.yml

- Github Actions를 활용한 자동 배포 세팅
- deploy.yml 파일 추가
3. [ ] 기타:
- Closes #195

Feat: #195 백엔드 자동 배포 세팅

---

.github/workflows/deploy.yml

- 단순 쉘 명령 실행은 uses 대신 run
- 
3. [ ] 기타:
- Closes #

Fix: #195 빌드 실패 해결

---

.github/workflows/deploy.yml

- ssh 비밀키 적용하는 부분이 빠져있었음
3. [ ] 기타:
- Closes #

Fix: 배포 실패 해결

---

.github/workflows/deploy.yml

- rsync 대신 scp 사용 테스트
3. [ ] 기타:
- Closes #

Fix: 파일 복사 시간이 너무 오래 걸리는 문제 해결

---

src/main/java/site/campingon/campingon/camp/controller/mongodb/SearchInfoController.java
src/main/java/site/campingon/campingon/camp/mapper/mongodb/SearchInfoMapper.java
src/main/java/site/campingon/campingon/camp/repository/mongodb/SearchInfoRepository.java
src/main/java/site/campingon/campingon/camp/service/mongodb/SearchInfoService.java

매퍼를 이용해 MongoDB SearchInfo를 CampListResponseDto로 매핑
- SearchInfo 서비스, 컨트롤러에서 CampListResponseDto로 반환 + 필요 repository 수정
- SearchInfoController 페이지네이션 복구
3. [ ] 기타:
- Closes #182

Feat/#182 MongoDB 데이터 CampListResponseDto로 매핑

---

src/main/java/site/campingon/campingon/camp/controller/CampController.java
src/main/java/site/campingon/campingon/camp/service/CampService.java
src/main/java/site/campingon/campingon/camp/utils/AuthenticateUser.java
src/main/java/site/campingon/campingon/common/config/SecurityPath.java
src/main/java/site/campingon/campingon/common/util/AuthenticateUser.java

- SecurityContextHolder 사용
- camp Utils 패키지 추가
3. [ ] 기타:
- Closes #191

feat : #191 캠핑장인기목록 조회 수정

---

.github/workflows/deploy.yml
src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
src/main/resources/application-prod.yml

Fix: #195 배포 세팅 변경

---

src/main/java/site/campingon/campingon/camp/dto/CampSiteListResponseDto.java
src/main/java/site/campingon/campingon/camp/dto/CampSiteResponseDto.java
src/main/java/site/campingon/campingon/camp/entity/Induty.java
src/main/java/site/campingon/campingon/camp/mapper/CampSiteMapper.java
src/main/java/site/campingon/campingon/camp/repository/CampSiteRepository.java
src/main/java/site/campingon/campingon/camp/service/CampSiteReserveService.java
src/main/java/site/campingon/campingon/common/config/SecurityPath.java
src/main/java/site/campingon/campingon/common/converter/CheckTimeConverter.java
src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/reservation/controller/ReservationController.java
src/main/java/site/campingon/campingon/reservation/dto/CampSiteResponseDto.java
src/main/java/site/campingon/campingon/reservation/dto/ReservationCancelRequestDto.java
src/main/java/site/campingon/campingon/reservation/dto/ReservationResponseDto.java
src/main/java/site/campingon/campingon/reservation/entity/CheckTime.java
src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
src/main/java/site/campingon/campingon/reservation/mapper/ReservationMapper.java
src/main/java/site/campingon/campingon/reservation/service/ReservationService.java
src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java
src/main/java/site/campingon/campingon/reservation/utils/ReservationValidate.java
src/test/java/site/campingon/campingon/reservation/service/ReservationServiceTest.java

reservation  Time 타입 매핑 에러 해결
- 에러코드 추가
- 예약 서비스 로직 json 반환 확인하면서 에러 해결
- induty json 반환시 한글명으로 반환하게 수정
- 캠핑지 반환 객체에 체크인,아웃시간 명시 (저번에 잘 못 삭제했던것같아요 죄송..)
3. [ ] 기타:
- Closes #189  Closes #202

Refactor/#189 reservation Time 타입 매핑 에러 해결

---

src/main/java/site/campingon/campingon/common/config/SecurityConfig.java
src/main/java/site/campingon/campingon/common/config/SecurityPath.java
src/main/java/site/campingon/campingon/common/jwt/CustomAccessDeniedHandler.java
src/main/java/site/campingon/campingon/common/jwt/CustomAuthenticationEntryPoint.java

`/api/users/me`가 permitAll로 들어가서 발생하던 문제 해결
- api/users/me 빠져있던 부분 추가
3. [ ] 기타:
- Closes #206

Fix: #206 Entry point withelist 추가

---

src/main/java/site/campingon/campingon/common/config/SecurityPath.java
src/main/java/site/campingon/campingon/common/oauth/handler/CustomOAuthSuccessHandler.java
src/main/resources/application-prod.yml

- RefreshToken JWT -> UUID로 변경하면서 user 이메일 받아오는 부분 변경
- 환경 변수 설정 (application-prod.yml)
3. [ ] 기타:
- Closes #211

Feat: #211 Google Oauth 로그인 수정

---

src/main/java/site/campingon/campingon/camp/controller/CampSiteController.java
src/main/java/site/campingon/campingon/camp/entity/CampSite.java

캠프사이트 isAvailable 디폴트 true로 수정, api 수정
3. [ ] 기타:
- Closes #

refactor: 캠프사이트 isAvailable 디폴트 true로 수정, api 수정

---

src/main/java/site/campingon/campingon/reservation/controller/ReservationController.java
src/main/resources/application.yml

@jhYun505 요청
3. [ ] 기타:
- Closes #

fix: 예약리스트 조회 page 요청 허용

---

src/main/java/site/campingon/campingon/bookmark/controller/BookMarkController.java
src/main/java/site/campingon/campingon/bookmark/entity/Bookmark.java
src/main/java/site/campingon/campingon/bookmark/service/BookmarkService.java
src/main/java/site/campingon/campingon/camp/repository/CampRepository.java
src/main/java/site/campingon/campingon/camp/service/CampService.java
src/test/java/site/campingon/campingon/camp/service/CampServiceTest.java

- 찜버튼을 눌러도 취소가 정상적으로 작동한다.
3. [ ] 기타:
- Closes #218

Fix/#218 찜 눌렀을시 취소 안되는 문제 BE

---

src/main/java/site/campingon/campingon/reservation/controller/ReservationController.java
src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
src/main/java/site/campingon/campingon/reservation/service/ReservationService.java
src/main/java/site/campingon/campingon/reservation/service/ReservationServiceImpl.java

다가오는 예약 조회 api 구현
3. [ ] 기타:
- Closes #221

feat: #221 다가오는 예약 조회 api 구현

---

src/main/resources/application-prod.yml

Feat: #211 환경변수 세팅

---

.github/workflows/blue-green-deploy.yml
Dockerfile
docker-compose.yml

Closes #229
3. [ ] 기타:
- Closes #

Feat: #229 Docker 활용 배포 테스트

---

.github/workflows/blue-green-deploy.yml

Closes #229
3. [ ] 기타:
- Closes #

Feat: #229 브랜치 변경

---

.github/workflows/blue-green-deploy.yml

Closes #229
3. [ ] 기타:
- Closes #

Typo: 오타 수정

---

.github/workflows/blue-green-deploy.yml

Closes #229
3. [ ] 기타:
- Closes #

Typo: 환경변수 직접 사용으로 변경

---

.github/workflows/blue-green-deploy.yml

Closes #229
3. [ ] 기타:
- Closes #

Typo: 쌍따옴표 추가

---

src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
src/main/java/site/campingon/campingon/common/util/AuthenticateUser.java

Fix/#235스케줄러에서 이미지 저장할때 모든 데이터를 계속 저장하는문제

---

src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingDataDto.java
src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
src/main/java/site/campingon/campingon/common/util/AuthenticateUser.java

- 데이터 더이상 가지고 오지 못할때 생기는문제를 해결한다.
3. [ ] 기타:
- #169

Fix/#169 데이터 더이상 가지고 오지 못할때 생기는문제

---

src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/common/jwt/JwtTokenProvider.java
src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/dto/GoCampingDataDto.java
src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java
src/main/java/site/campingon/campingon/common/util/AuthenticateUser.java
src/main/java/site/campingon/campingon/user/controller/UserController.java
src/main/java/site/campingon/campingon/user/service/UserAuthService.java
src/main/java/site/campingon/campingon/user/service/UserService.java

- 로깅레벨을 변경하여 배포시 로깅으로인한 성능저하를 방지한다.
3. [ ] 기타:
- Closes #241

Feat/#241 로깅레벨 변경

---

src/main/java/site/campingon/campingon/camp/service/mongodb/SearchInfoService.java

Fix: #251 DTO 일부 수정

---

src/main/java/site/campingon/campingon/common/config/SecurityPath.java
src/main/java/site/campingon/campingon/reservation/dto/ReservationResponseDto.java
src/main/java/site/campingon/campingon/reservation/dto/ReviewResponseDto.java
src/main/java/site/campingon/campingon/reservation/entity/Reservation.java
src/main/java/site/campingon/campingon/reservation/mapper/ReservationMapper.java
src/main/java/site/campingon/campingon/reservation/repository/ReservationRepository.java
src/main/java/site/campingon/campingon/review/dto/ReviewResponseDto.java
src/main/java/site/campingon/campingon/review/entity/Review.java
src/main/java/site/campingon/campingon/review/mapper/ReviewMapper.java

사용자의 예약목록에서 리뷰 유무 정보 반환을 통해 리뷰 작성, 수정, 조회 판단
3. [ ] 기타:
ERD 수정 
- Closes #239

Feat/#239 사용자의 예약목록에서 리뷰 유무 정보 반환

---

src/main/java/site/campingon/campingon/camp/entity/Camp.java
src/main/java/site/campingon/campingon/camp/entity/CampAddr.java
src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

- 캠프테이블 erd 변경
3. [ ] 기타:
- Closes #254

Fix/#254 erd 변경

---

src/main/java/site/campingon/campingon/common/exception/ErrorCode.java
src/main/java/site/campingon/campingon/common/public_data/controller/GoCampingController.java
src/main/java/site/campingon/campingon/common/public_data/schedule/GoCampingScheduler.java
src/main/java/site/campingon/campingon/common/public_data/service/GoCampingService.java

- 빈 api 호출시 에러 발생 문제 해결
- 고캠핑 스케줄러, 컨트롤러, 서비스 로직 변경
3. [ ] 기타:
- Closes #169

Fix/#169  빈 api 호출시 에러 발생 문제 해결
